create DATABASE IF NOT EXISTS RAILWAY;
USE RAILWAY;
CREATE TABLE STATIONS(
  station_ID INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50),
  city VARCHAR(50),
  state VARCHAR(50),
  country VARCHAR(50),
  PRIMARY KEY (station_ID)
);
